### ISSUE TITLE
Darwin Support

### ISSUE THREAD

**Issue by Ex0D** [Ex0D/AutoUpdater-NodeJS#5]
### Tasks : 
- [x] Check with `process.platform` if the user is on MAC
- [x] Check if NVM env variable is good (need more documentation)
- [x] Return same exec process than linux for install / update
